### ISSUE TITLE
Visualizer App not running

### ISSUE THREAD

**Issue by mrivera-ms** [BigThinkcode/AdaptiveCards#85] opened 2022-05-20 02:03 UTC
### Target Platforms

Android, Other

### SDK Version

adaptivecards-reactnative 2.2.24

### Application Name

Visualizer

### Problem Description

The Visualizer App does not start as expected by following steps listed in the following [README](https://github.com/BigThinkcode/AdaptiveCards/tree/fork-main/source/community/reactnative#examples--visualizer). Metro is started. Running Android emulator. Please see screenshot below.

### Screenshots

![image](https://user-images.githubusercontent.com/44449640/169433858-6a0ca31b-1229-4686-b778-24cb3a74a97f.png)

![image](https://user-images.githubusercontent.com/44449640/169432605-f951fae7-6a72-47bc-b6fb-ee9975843b3c.png)

### Card JSON

```JSON
n/a
```

**Comment by Vasanth-S** [comment] 2022-06-21 09:48
@mrivera-ms Are you still facing this issue? If not resolved, @Zaidos9 from MS team can help you.

**Comment by mrivera-ms** [comment] 2022-06-28 17:31
@Vasanth-S, I found that the issue does not appear on Android emulators running API level 27 (Oreo).  Still facing this issue using Android emulator API 28, 29, 30 and up.

**Comment by Zaidos9** [comment] 2022-08-01 15:18
On Android, the visualizer app can be run by adding following under `application` tag in `source/community/reactnative/android/app/src/main/AndroidManifest.xml`

`android:usesCleartextTraffic="true"`

**Comment by pragadeeshk** [comment] 2022-08-01 16:38
@Zaidos9 Thats right. We have a PR for that. yet to merge. It should be resolved soon.

**Comment by pragadeeshk** [comment] 2022-08-05 07:27
@mrivera-ms, This is resolved in latest release branch reactnative/release-2.2.27. Please try it out once and share your observation.

**Comment by Vasanth-S** [comment] 2022-08-07 11:04
Fixed in release-2.2.27. @mrivera-ms Reopen if the issue is not resolved.

**Closed as completed by Vasanth-S** 2022-08-07 11:04 UTC
